### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by zhjy2016** [hetaoconquer/BGAN#10]
thanks for sharing your code, 
The results of my own training map on cifar10 is 4% less than yours. May I get your trained model please?

**Comment by ht014** [comment]
Hi,

Sorry for the late response.  since this project was three years ago and I
graduated from my previous university two years ago, I cannot get access to
the training model.
Can you provide your training settings in detail, such as how to calculate
the similarity matrix, how to initialize the model, or how to calculate the
MAP.

zhjy2016 <notifications@github.com> 于2020年4月20日周一 上午11:25写道：
